#!/bin/bash
THRESHOLD=90
EMAIL="prajwalmallur1017.com"
USAGE=$(df / | grep / | awk '{ print $5 }' | sed 's/%//g')

if [ "$USAGE" -ge "$THRESHOLD" ]; then
  echo "Warning: Disk usage has reached $USAGE%. Please take necessary action." | mail -s "Disk Usage Alert" $EMAIL
fi
